.PHONY: clean All

All:
	@echo "----------Building project:[ basicio - Debug ]----------"
	@cd "basicio" && "$(MAKE)" -f  "basicio.mk"
clean:
	@echo "----------Cleaning project:[ basicio - Debug ]----------"
	@cd "basicio" && "$(MAKE)" -f  "basicio.mk" clean
