.PHONY: clean All

All:
	@echo "----------Building project:[ simple_recursion - Debug ]----------"
	@cd "simple_recursion" && "$(MAKE)" -f  "simple_recursion.mk"
clean:
	@echo "----------Cleaning project:[ simple_recursion - Debug ]----------"
	@cd "simple_recursion" && "$(MAKE)" -f  "simple_recursion.mk" clean
