.PHONY: clean All

All:
	@echo "----------Building project:[ Redifining_base_class_methods - Debug ]----------"
	@cd "Redifining_base_class_methods" && "$(MAKE)" -f  "Redifining_base_class_methods.mk"
clean:
	@echo "----------Cleaning project:[ Redifining_base_class_methods - Debug ]----------"
	@cd "Redifining_base_class_methods" && "$(MAKE)" -f  "Redifining_base_class_methods.mk" clean
