.PHONY: clean All

All:
	@echo "----------Building project:[ Bank_ManagementSystem - Debug ]----------"
	@cd "Bank_ManagementSystem" && "$(MAKE)" -f  "Bank_ManagementSystem.mk"
clean:
	@echo "----------Cleaning project:[ Bank_ManagementSystem - Debug ]----------"
	@cd "Bank_ManagementSystem" && "$(MAKE)" -f  "Bank_ManagementSystem.mk" clean
