.PHONY: clean All

All:
	@echo "----------Building project:[ string_assigntest - Debug ]----------"
	@cd "string_assigntest" && "$(MAKE)" -f  "string_assigntest.mk"
clean:
	@echo "----------Cleaning project:[ string_assigntest - Debug ]----------"
	@cd "string_assigntest" && "$(MAKE)" -f  "string_assigntest.mk" clean
