.PHONY: clean All

All:
	@echo "----------Building project:[ static_class_members - Debug ]----------"
	@cd "static_class_members" && "$(MAKE)" -f  "static_class_members.mk"
clean:
	@echo "----------Cleaning project:[ static_class_members - Debug ]----------"
	@cd "static_class_members" && "$(MAKE)" -f  "static_class_members.mk" clean
