.PHONY: clean All

All:
	@echo "----------Building project:[ mystring_insertion_extraction - Debug ]----------"
	@cd "mystring_insertion_extraction" && "$(MAKE)" -f  "mystring_insertion_extraction.mk"
clean:
	@echo "----------Cleaning project:[ mystring_insertion_extraction - Debug ]----------"
	@cd "mystring_insertion_extraction" && "$(MAKE)" -f  "mystring_insertion_extraction.mk" clean
