.PHONY: clean All

All:
	@echo "----------Building project:[ logical_operator - Debug ]----------"
	@cd "logical_operator" && "$(MAKE)" -f  "logical_operator.mk"
clean:
	@echo "----------Cleaning project:[ logical_operator - Debug ]----------"
	@cd "logical_operator" && "$(MAKE)" -f  "logical_operator.mk" clean
