.PHONY: clean All

All:
	@echo "----------Building project:[ iterating_hashmap - Debug ]----------"
	@cd "iterating_hashmap" && "$(MAKE)" -f  "iterating_hashmap.mk"
clean:
	@echo "----------Cleaning project:[ iterating_hashmap - Debug ]----------"
	@cd "iterating_hashmap" && "$(MAKE)" -f  "iterating_hashmap.mk" clean
