.PHONY: clean All

All:
	@echo "----------Building project:[ stringpass_function - Debug ]----------"
	@cd "stringpass_function" && "$(MAKE)" -f  "stringpass_function.mk"
clean:
	@echo "----------Cleaning project:[ stringpass_function - Debug ]----------"
	@cd "stringpass_function" && "$(MAKE)" -f  "stringpass_function.mk" clean
