.PHONY: clean All

All:
	@echo "----------Building project:[ disarium_number - Debug ]----------"
	@cd "disarium_number" && "$(MAKE)" -f  "disarium_number.mk"
clean:
	@echo "----------Cleaning project:[ disarium_number - Debug ]----------"
	@cd "disarium_number" && "$(MAKE)" -f  "disarium_number.mk" clean
