.PHONY: clean All

All:
	@echo "----------Building project:[ section12_pointers - Debug ]----------"
	@cd "section12_pointers" && "$(MAKE)" -f  "section12_pointers.mk"
clean:
	@echo "----------Cleaning project:[ section12_pointers - Debug ]----------"
	@cd "section12_pointers" && "$(MAKE)" -f  "section12_pointers.mk" clean
