.PHONY: clean All

All:
	@echo "----------Building project:[ interfaces - Debug ]----------"
	@cd "interfaces_start" && "$(MAKE)" -f  "interfaces.mk"
clean:
	@echo "----------Cleaning project:[ interfaces - Debug ]----------"
	@cd "interfaces_start" && "$(MAKE)" -f  "interfaces.mk" clean
