.PHONY: clean All

All:
	@echo "----------Building project:[ firstprogram - Debug ]----------"
	@cd "section4_workspace" && "$(MAKE)" -f  "firstprogram.mk"
clean:
	@echo "----------Cleaning project:[ firstprogram - Debug ]----------"
	@cd "section4_workspace" && "$(MAKE)" -f  "firstprogram.mk" clean
