.PHONY: clean All

All:
	@echo "----------Building project:[ Arrays_intro - Debug ]----------"
	@cd "Arrays_intro" && "$(MAKE)" -f  "Arrays_intro.mk"
clean:
	@echo "----------Cleaning project:[ Arrays_intro - Debug ]----------"
	@cd "Arrays_intro" && "$(MAKE)" -f  "Arrays_intro.mk" clean
