.PHONY: clean All

All:
	@echo "----------Building project:[ for_pattern - Debug ]----------"
	@cd "for_pattern" && "$(MAKE)" -f  "for_pattern.mk"
clean:
	@echo "----------Cleaning project:[ for_pattern - Debug ]----------"
	@cd "for_pattern" && "$(MAKE)" -f  "for_pattern.mk" clean
