.PHONY: clean All

All:
	@echo "----------Building project:[ function_KMPL - Debug ]----------"
	@cd "function_KMPL" && "$(MAKE)" -f  "function_KMPL.mk"
clean:
	@echo "----------Cleaning project:[ function_KMPL - Debug ]----------"
	@cd "function_KMPL" && "$(MAKE)" -f  "function_KMPL.mk" clean
